# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Mohammed Mutaher
name: Mohammed Mutaher
position: Graduate Student, Cancer Immunology Researcher, Memorial Sloan Kettering Cancer Center
email: mutaherm@mskcc.org
description: >-
  I am an aspiring scientist working at the intersection of cancer biology and immunology.
  <br>
  I am currently a graduate student in the Cancer Biology PhD program at the [Gerstner Sloan Kettering Graduate School of Biomedical Sciences](https://www.sloankettering.edu/gerstner). My thesis work is in the lab of [Ivan Maillard](https://www.mskcc.org/research-areas/labs/ivan-maillard) where I am studying the role of Notch signaling in anti-cancer immunity and immunobiology of lymph node fibroblastic reticular cells. 
  Previously, I was a research associate at the [Broad Institute of MIT and Harvard](https://www.broadinstitute.org) in the lab of [Nir Hacohen](https://hacohenlab.mgh.harvard.edu/) where I worked on several collaborative and interdisciplinary projects studying naive CD8 T cell differentiation in tumors.
  
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://mohammedmutaher.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
github_username: mohammedmutaher
linkedin_url: https://www.linkedin.com/in/mohammed-mutaher-80b87218a/
google_scholar: 397BkIgAAAAJ
# twitter_username: srijitseal
# google_analytics: G-8Z8BB08Y56

# Build settings
theme: minima
plugins:
  - jekyll-feed

sass:
  style: compact

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
